# -*- coding: utf-8 -*-
"""Untitled60.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qmBVST09h3BT4hdXrXTQXexGxYL-Myz6
"""

import numpy as np
import matplotlib.pyplot as plt

# --- MICROGRID TOPOLOGY (Graph Theory) ---
# Adjacency Matrix (Ring Topology: 0-1-2-3-0)
adj = np.array([[0, 1, 0, 1],
                [1, 0, 1, 0],
                [0, 1, 0, 1],
                [1, 0, 1, 0]])

# --- ROBUST PARAMETERS ---
n_nodes = 4
freq_ref = 60.0
k_coupling = 0.45
alpha_damping = 0.2     # Local stability factor
max_delay_steps = 50    # 0.5 seconds at dt=0.01
dt, t_end = 0.01, 15.0
t_span = np.arange(0, t_end, dt)


freqs = np.array([60.5, 59.2, 60.8, 59.7])
history = [freqs.copy() for _ in range(max_delay_steps + 1)]
results = []

# --- SIMULATION ENGINE ---
for t in t_span:

    current_delay = 40 if t > 5.0 else 10


    delayed_freqs = history[-current_delay]

    new_freqs = freqs.copy()
    for i in range(n_nodes):

        neighbor_sum = 0
        for j in range(n_nodes):
            if adj[i, j] == 1:
                neighbor_sum += (delayed_freqs[j] - freqs[i])


        d_freq = -alpha_damping * (freqs[i] - freq_ref) + k_coupling * neighbor_sum
        new_freqs[i] += d_freq * dt

    freqs = new_freqs
    history.append(freqs.copy())
    history.pop(0)
    results.append(freqs.copy())


results = np.array(results)
plt.figure(figsize=(12, 6))
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']
for i in range(n_nodes):
    plt.plot(t_span, results[:, i], color=colors[i], lw=2, label=f'Inverter {i+1}')

plt.axhline(60, color='black', ls='--', alpha=0.6, label='Nominal 60Hz')
plt.fill_between(t_span, 59.9, 60.1, color='gray', alpha=0.1, label='Utility Tolerance')
plt.title('Robust Synchronization: 4-Node Microgrid with Cloud Latency', fontsize=14)
plt.xlabel('Time (s)'); plt.ylabel('Frequency (Hz)'); plt.legend(loc='upper right')
plt.grid(True, alpha=0.3)
plt.show()

print(f"Final Frequency Deviation: {np.max(np.abs(freqs - 60.0)):.5f} Hz")